import socket
import struct
import time
import re
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey, X25519PublicKey
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305

def read_frame(s):
    hdr = s.recv(4)
    if not hdr or len(hdr) < 4:
        return None, None
    length = struct.unpack(">I", hdr)[0]
    data = b""
    while len(data) < length:
        chunk = s.recv(length - len(data))
        if not chunk:
            break
        data += chunk
    frame_type = data[0]
    payload = data[1:]
    return frame_type, payload

def encode_frame(frame_type, payload=b""):
    length = 1 + len(payload)
    return struct.pack(">IB", length, frame_type) + payload

class NonceCounter:
    def __init__(self):
        self.counter = 0
    def next_nonce(self):
        self.counter += 1
        return struct.pack(">Q", self.counter).rjust(12, b"\x00")

def get_latest_pin():
    time.sleep(0.5)
    with open("/tmp/mac_agent_live.log", "r") as f:
        content = f.read()
    matches = re.findall(r"generated pairing PIN: (\d{6})", content)
    if matches:
        return matches[-1]
    return None

def main():
    host = "192.168.1.9"
    port = 7878
    print(f"=== ELYSIUM NEXUS END-TO-END CONTROL TEST ===")
    print(f"[*] Opening TCP connection to Mac Agent at {host}:{port}...")
    s = socket.create_connection((host, port), timeout=5)

    # 1. Send HELLO with client Curve25519 public key
    client_priv = X25519PrivateKey.generate()
    client_pub_bytes = client_priv.public_key().public_bytes_raw()
    s.sendall(encode_frame(0x01, client_pub_bytes))
    print(f"[+] Sent HELLO frame (client pubkey: {client_pub_bytes.hex()[:16]}...)")

    # 2. Receive HELLO_ACK from server
    ftype, ack_payload = read_frame(s)
    assert ftype == 0x02, f"Expected HELLO_ACK (0x02), got {ftype}"
    server_pub_bytes = ack_payload
    print(f"[+] Received HELLO_ACK frame (server pubkey: {server_pub_bytes.hex()[:16]}...)")

    # 3. Derive channel key (ECDH + HKDF)
    server_pub = X25519PublicKey.from_public_bytes(server_pub_bytes)
    shared_secret = client_priv.exchange(server_pub)
    hkdf = HKDF(
        algorithm=hashes.SHA256(),
        length=32,
        salt=b"elysium-nexus-v1",
        info=b"elysium-channel"
    )
    channel_key = hkdf.derive(shared_secret)
    print(f"[+] ECDH + HKDF-SHA256 channel key derived: {channel_key.hex()[:16]}...")

    cipher = ChaCha20Poly1305(channel_key)
    nonce_gen = NonceCounter()

    # 4. Get PIN generated by Mac Agent
    pin = get_latest_pin()
    if not pin:
        print("[!] Failed to read PIN from agent log.")
        return
    print(f"[+] Mac Agent generated pairing PIN: {pin}")

    # 5. Send 6 encrypted PIN_DIGIT frames
    print(f"[*] Sending 6 encrypted PIN_DIGIT frames for PIN {pin}...")
    for index, d in enumerate(pin):
        digit_byte = int(d).to_bytes(1, "big")
        nonce = nonce_gen.next_nonce()
        sealed = cipher.encrypt(nonce, digit_byte, None)
        s.sendall(encode_frame(0x03, nonce + sealed))
        print(f"  -> PIN digit {index+1}/6 ({d}) encrypted & sent")
        time.sleep(0.05)

    # 6. Read PAIR_OK response
    ftype, resp_payload = read_frame(s)
    assert ftype == 0x04, f"Expected PAIR_OK (0x04), got {ftype}"
    nonce = resp_payload[:12]
    body_and_tag = resp_payload[12:]
    plain = cipher.decrypt(nonce, body_and_tag, None)
    assert plain[0] == 1, "Pairing rejected by server!"
    print(" [✓] PAIR_OK RECEIVED! MAC AGENT ACCEPTED PAIRING PIN! ENCRYPTED CHANNEL IS OPEN!\n")

    # 7. Test Mouse Movement (Trackpad dx=100, dy=100)
    print("[*] TEST 1: Sending Mouse / Trackpad Movement (dx=100, dy=100)...")
    mouse_payload = struct.pack(">ff", 100.0, 100.0)
    nonce = nonce_gen.next_nonce()
    s.sendall(encode_frame(0x05, nonce + cipher.encrypt(nonce, mouse_payload, None)))
    time.sleep(0.3)

    # 8. Test Trackpad Scroll (dx=0, dy=-15)
    print("[*] TEST 2: Sending Trackpad Scroll (dy=-15)...")
    scroll_payload = struct.pack(">ff", 0.0, -15.0)
    nonce = nonce_gen.next_nonce()
    s.sendall(encode_frame(0x07, nonce + cipher.encrypt(nonce, scroll_payload, None)))
    time.sleep(0.3)

    # 9. Test Mouse Left Click (down + up)
    print("[*] TEST 3: Sending Mouse Left Click...")
    down_payload = struct.pack(">BB", 0, 1) # left down
    nonce = nonce_gen.next_nonce()
    s.sendall(encode_frame(0x06, nonce + cipher.encrypt(nonce, down_payload, None)))
    time.sleep(0.1)
    up_payload = struct.pack(">BB", 0, 0) # left up
    nonce = nonce_gen.next_nonce()
    s.sendall(encode_frame(0x06, nonce + cipher.encrypt(nonce, up_payload, None)))
    time.sleep(0.3)

    # 10. Test Keyboard Key Press (Space bar: hidUsage=0x2C)
    print("[*] TEST 4: Sending Keyboard Space Key Press...")
    key_down = struct.pack(">BII", 0, 0x2C, 0) # space down
    nonce = nonce_gen.next_nonce()
    s.sendall(encode_frame(0x08, nonce + cipher.encrypt(nonce, key_down, None)))
    time.sleep(0.1)
    key_up = struct.pack(">BII", 1, 0x2C, 0) # space up
    nonce = nonce_gen.next_nonce()
    s.sendall(encode_frame(0x08, nonce + cipher.encrypt(nonce, key_up, None)))
    time.sleep(0.3)

    # 11. Test Pinch Zoom Gesture (factor=1.2)
    print("[*] TEST 5: Sending Pinch Zoom Gesture (factor=1.2)...")
    pinch_payload = struct.pack(">f", 1.2)
    nonce = nonce_gen.next_nonce()
    s.sendall(encode_frame(0x09, nonce + cipher.encrypt(nonce, pinch_payload, None)))
    time.sleep(0.3)

    print("\n [✓] ALL CONTROL TESTS COMPLETED SUCCESSFULLY! MOUSE, KEYBOARD & TRACKPAD ARE FULLY OPERATIONAL!")
    s.close()

if __name__ == "__main__":
    main()
